version: '3.7'
services:
  handler:
    image: collage-handler
    container_name: collage-handler
    build:
      context: ./collage_maker
      dockerfile: ./handler.Dockerfile
    volumes:
      - ./collage_maker/handler:/opt/app/handler
  api:
    image: collage-api
    container_name: collage-api
    build:
      context: ./collage_maker
      dockerfile: ./api.Dockerfile
    ports:
      - 8787:8000
    volumes:
      - ./collage_maker/api:/opt/app/api
    depends_on:
      - handler
  ui:
    image: collage-ui
    container_name: collage-ui
    build:
      context: ./collage_maker
      dockerfile: ./ui.Dockerfile
    ports:
      - 8788:8788
    volumes:
      - ./collage_maker/ui/src:/opt/app/src
    depends_on:
      - api