version: '3.7'
services:
  collage_maker:
    image: bron-collage-maker
    container_name: bron-collage-maker
    build:
      context: ./cc
      dockerfile: ./cm.Dockerfile
    volumes:
      - ./cc/cm:/opt/app/cm
  api:
    image: bron-api
    container_name: bron-api
    build:
      context: ./cc
      dockerfile: ./api.Dockerfile
    ports:
      - 8787:8000
    volumes:
      - ./cc/api:/opt/app/api
    depends_on:
      - collage_maker
  ui:
    image: bron-ui
    container_name: bron-ui
    build:
      context: ./cc
      dockerfile: ./ui.Dockerfile
    ports:
      - 8788:8788
    volumes:
      - ./cc/ui/src:/opt/app/src
    depends_on:
      - api