version: '3.7'
services:
  app:
    image: collage-maker
    container_name: collage-maker
    environment:
      GIT_HUB_KEY: ${GIT_HUB_KEY}
      GIT_HUB_SEARCH_QUERY: google
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./collage_maker:/opt/app/collage_maker
      - ./avatars:/tmp/avatars